export default () => ({
  port: parseInt(process.env.PORT ?? '8080', 10),
  nodeEnv: process.env.NODE_ENV ?? 'development',
  frontendBaseUrl: process.env.FRONTEND_BASE_URL ?? 'http://localhost:3000',
  backendBaseUrl: process.env.BACKEND_BASE_URL ?? 'http://localhost:8080',
  corsOrigin: process.env.CORS_ORIGIN ?? 'http://localhost:3000',
  jwtSecret: process.env.JWT_SECRET ?? 'change-this-secret-in-production',
  jwtExpiresIn: process.env.JWT_EXPIRES_IN ?? '1d',
  adminDefaultEmail: process.env.ADMIN_DEFAULT_EMAIL ?? 'admin@example.com',
  adminDefaultPassword: process.env.ADMIN_DEFAULT_PASSWORD ?? 'Admin@123456',
  uploadDriver: process.env.UPLOAD_DRIVER ?? 'local',
  maxUploadSizeMb: parseInt(process.env.MAX_UPLOAD_SIZE_MB ?? '5', 10),
  maxVideoUploadSizeMb: parseInt(
    process.env.MAX_VIDEO_UPLOAD_SIZE_MB ?? '30',
    10,
  ),
  r2AccountId: process.env.R2_ACCOUNT_ID,
  r2Endpoint: process.env.R2_ENDPOINT,
  r2AccessKeyId: process.env.R2_ACCESS_KEY_ID,
  r2SecretAccessKey: process.env.R2_SECRET_ACCESS_KEY,
  r2Bucket: process.env.R2_BUCKET,
  r2PublicBaseUrl: process.env.R2_PUBLIC_BASE_URL,
  r2Region: process.env.R2_REGION ?? 'auto',
  awsS3Region: process.env.AWS_S3_REGION ?? 'us-east-1',
  awsS3AccessKeyId: process.env.AWS_S3_ACCESS_KEY_ID,
  awsS3SecretAccessKey: process.env.AWS_S3_SECRET_ACCESS_KEY,
  awsS3Bucket: process.env.AWS_S3_BUCKET,
  awsS3PublicBaseUrl: process.env.AWS_S3_PUBLIC_BASE_URL,
  bodyLimit: process.env.BODY_LIMIT ?? '1mb',
  mailjetApiKey: process.env.MAILJET_API_KEY,
  mailjetApiSecret: process.env.MAILJET_API_SECRET,
  mailjetFromEmail: process.env.MAILJET_FROM_EMAIL,
  mailjetFromName: process.env.MAILJET_FROM_NAME ?? 'Enchanted Energy Store',
  contactNotificationEmail: process.env.CONTACT_NOTIFICATION_EMAIL,
  revalidateSecret: process.env.REVALIDATE_SECRET,
});
